config_enabled: false
description: Disabled configuration for testing purposes
cloud:
  provider: aws
  s3_bucket: ct-carasso-poc
extraction_file:
  file_format: csv
database_connection:
  engine: mysql+pymysql
  host: localhost
  port: 3307
  username: root
  password: mysql_password
  database: fakeDatabase
tables:
  - table_name: users
    mode: full_load
  - table_name: Products
    mode: full_load