config_enabled: true
extraction_file:
  file_format: csv
database_connection:
  engine: mysql+pymysql
  host: localhost
  port: 3307
  username: root
  password: mysql_password
  database: fakeDatabase
tables:
  - table_name: users
    mode: full_load
  - table_name: Products
    mode: full_load