config_enabled: true
description: TAFNIT 50 Replication Configuration
cloud:
  provider: aws
  s3_bucket: ct-carasso-poc
extraction_file:
  file_format: csv
database_connection:
  engine: mysql+pymysql
  host: localhost
  port: 3307
  username: root
  password: mysql_password
  database: tafnit_50
tables:
  - table_name: users
    ingestion_mode: full_load
  - table_name: products
    ingestion_mode: full_load
  - table_name: orders 
    ingestion_mode: full_load
  - table_name: categories
    ingestion_mode: full_load
  - table_name: reviews
    ingestion_mode: full_load
  - table_name: product_category_links
    ingestion_mode: full_load