CREATE OR REPLACE WAREHOUSE INGESTION_WH
WITH
    WAREHOUSE_TYPE = STANDARD
    SCALING_POLICY = ECONOMY
    WAREHOUSE_SIZE = XSMALL
    RESOURCE_CONSTRAINT = STANDARD_GEN_1
    AUTO_SUSPEND = 30
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 2
    AUTO_RESUME = TRUE
    COMMENT = 'Warehouse used for ingesting data from Tafnit into Snowflake';
GRANT USAGE ON WAREHOUSE INGESTION_WH TO USER SPN_CACHE_REPLICATION;