-- View where user can check if table was refreshed and is updated
CREATE SCHEMA IF NOT EXISTS RAW.ADMIN;
CREATE VIEW IF NOT EXISTS RAW.ADMIN.LOAD_HISTORY AS
SELECT 
    SCHEMA_NAME,
    TABLE_NAME,
    STATUS,
    LAST_LOAD_TIME,
    ROW_COUNT,
    SPLIT_PART(FILE_NAME, '/' , -1) AS FILE_NAME,
    FIRST_ERROR_MESSAGE
    ERROR_COUNT
FROM RAW.INFORMATION_SCHEMA.LOAD_HISTORY
ORDER BY SCHEMA_NAME, TABLE_NAME, LAST_LOAD_TIME DESC;
