config_enabled: true
description: Postgres replication of sales and products data
cloud:
  provider: aws
  bucket: ct-carasso-poc
  partitionate_data: false
snowflake_connection:
  account: sw_account
  user: sw_user
  password: sw_password
  role: sw_role
  warehouse: COMPUTE_WH
  database: CARASSO_POC_DB
  schema: POSTGRES
  stages_type: external
  storage_integration: CT_CARASSO_AWS
database_connection:
  engine: postgresql+psycopg2
  host: localhost
  port: 5432
  username: postgres
  password: postgres_password
  database: postgres
  schema: public
extraction_file:
  local_storage_directory: tmp/
  file_format: csv
  exclude_file_after_uploading: true
tables:
  - table_name: customers
    where: customer_id <= 6
  - table_name: items
  - table_name: transactions
  - table_name: departments
  - table_name: product_reviews
  - table_name: item_department_links