config_enabled: false
description: TAFNIT 50 Replication Configuration
cloud:
  provider: aws
  bucket: ct-carasso-poc
  partitionate_data: true
snowflake_connection:
  account: sw_account
  user: sw_user
  password: sw_password
  role: sw_role
  warehouse: COMPUTE_WH
  database: CARASSO_POC_DB
  schema: TAFNIT_50
  storage_integration: CT_CARASSO_AWS
  stages_type: external
database_connection:
  engine: mysql+pymysql
  host: localhost
  port: 3307
  username: root
  password: mysql_password
  database: tafnit_50
extraction_file:
  local_storage_directory: tmp/
  file_format: csv
  exclude_file_after_uploading: true
tables:
  - table_name: users
  - table_name: products
  - table_name: orders 
  - table_name: categories
  - table_name: reviews
  - table_name: product_category_links