config_enabled: false
description: TAFNIT 116 Replication Configuration
snowflake_connection:
  account: sw_account
  user: sw_user
  password: sw_password
  role: sw_role
  warehouse: COMPUTE_WH
  database: CARASSO_POC_DB
  schema: TAFNIT_116
  storage_integration: CT_CARASSO_AWS
  stages_type: internal
database_connection:
  engine: mysql+pymysql
  host: localhost
  port: 3307
  username: root
  password: mysql_password
  database: tafnit_116
extraction_file:
  local_storage_directory: tmp/
  file_format: parquet
  exclude_file_after_uploading: true
tables:
  - table_name: users
  - table_name: products
    where: id = 1
  - table_name: orders
  - table_name: categories
  - table_name: reviews
  - table_name: product_categories