config_enabled: true
description: TAFNIT 116 Replication Configuration
cloud:
  provider: aws
  s3_bucket: ct-carasso-poc
snowflake_connection:
  account: sw_account
  user: sw_user
  password: sw_password
  role: sw_role
  warehouse: COMPUTE_WH
  database: CARASSO_POC_DB
  schema: TAFNIT_116
database_connection:
  engine: mysql+pymysql
  host: localhost
  port: 3307
  username: root
  password: mysql_password
  database: tafnit_116
extraction_file:
  file_format: parquet
  exclude_file_after_uploading: true
  upload_remaining_files: true
tables:
  - table_name: users
    ingestion_mode: full_load
  - table_name: products
    ingestion_mode: full_load
  - table_name: orders
    ingestion_mode: full_load
  - table_name: categories
    ingestion_mode: full_load
  - table_name: reviews
    ingestion_mode: full_load
  - table_name: product_categories
    ingestion_mode: full_load
  - table_name: product_categories_missing
    ingestion_mode: full_load