config_enabled: true
description: Postgres replication of sales and products data
cloud:
  provider: aws
  bucket: ct-carasso-poc
  upload_remaining_files: true
snowflake_connection:
  account: sw_account
  user: sw_user
  password: sw_password
  role: sw_role
  warehouse: COMPUTE_WH
  database: CARASSO_POC_DB
  schema: POSTGRES
  stages_type: internal
  upload_remaining_files: true
database_connection:
  engine: postgresql+psycopg2
  host: localhost
  port: 5432
  username: postgres
  password: postgres_password
  database: postgres
  schema: public
extraction_file:
  local_storage_directory: tmp/
  file_format: csv
  exclude_file_after_uploading: true
tables:
  - table_name: customers
    ingestion_mode: full_load
  - table_name: items
    ingestion_mode: full_load
  - table_name: transactions
    ingestion_mode: full_load
  - table_name: departments
    ingestion_mode: full_load
  - table_name: product_reviews
    ingestion_mode: full_load
  - table_name: item_department_links
    ingestion_mode: full_load